main_engine_configs:

  # Default configs for the main loop
  max_iteration_steps: 10
  input_field_test_value: "PyBA"
  headless_mode: False        # By default, doesn't run in the headless mode
  handle_dependencies: True   # By default, we try to install all the recommended dependencies
  enable_tracing: True        # By default, we allow for tracing of the activity
  exploratory_mode: False     # Will not be running in exploratory mode by default
  use_logger: False           # Will not use the logger by default
  trace_save_directory: "/tmp/pyba" # Saving the .zip file inside the /tmp/pyba directory unless specified by the user

  # Tracing configs
  tracing:
    screenshots: False # Capture screenshots
    snapshots: False   # Capture DOM snapshots
    sources: False     # Capture JS sources
    record_har_content: "omit"    # can also be omit if you don't want to include requests and responses

  # Default values for the LLMs
  vertexai:
    provider: "vertexai"
    model: "gemini-2.5-pro"
  openai:
    provider: "openai"
    model: "gpt-4o"

automated_login_configs:
  facebook:
    urls:
      - "https://www.facebook.com/login/"
      - "https://www.facebook.com/"
  instagram:
    urls:
      - "https://www.instagram.com/accounts/login/"
      - "https://www.instagram.com/"
    click_location:   # Change the location if your screen size is different, this will work as is for 1900x1280
      default_screen_height: 1280
      x_from_left: 1000
      y_from_bottom: 1000

process_config:
  selectors :
    - "input:not([type='hidden']):not([type='submit']):not([type='button']):not([type='reset']):not([type='file'])"
    - "textarea"
    - "select"
    - "[contenteditable='true']"
    - "[role='textbox']"
    - "[role='searchbox']"
    - "[role='combobox']"