main_engine_configs:

  # Default configs for the main loop
  max_iteration_steps: 10
  input_field_test_value: "PyBA"
  headless_mode: False        # By default, doesn't run in the headless mode
  handle_dependencies: True   # By default, we try to install all the recommended dependencies
  enable_tracing: True        # By default, we allow for tracing of the activity
  exploratory_mode: False     # Will not be running in exploratory mode by default
  use_logger: False           # Will not use the logger by default
  trace_save_directory: "/tmp/pyba" # Saving the .zip file inside the /tmp/pyba directory unless specified by the user

  # Tracing configs
  tracing:
    screenshots: False # Capture screenshots
    snapshots: False   # Capture DOM snapshots
    sources: False     # Capture JS sources
    record_har_content: "omit"    # can also be embed|attack if you want to include requests and responses

  # Default values for the LLMs
  vertexai:
    provider: "vertexai"
    model: "gemini-2.5-pro"
  openai:
    provider: "openai"
    model: "gpt-4o"

automated_login_configs:
  facebook:
    urls:
      - "https://www.facebook.com/login/"
      - "https://www.facebook.com/"
    username_selector: 'input[name="email"]'
    password_selector: 'input[name="pass"]'
    submit_selector: 'button[type="submit"]'
  instagram:
    urls:
      - "https://www.instagram.com/accounts/login/"
      - "https://www.instagram.com/"
    username_selector: 'input[name="username"]'   # These can be later defined as a list
    password_selector: 'input[name="password"]'
    submit_selector: 'button[type="submit"]'
    fall_back:
      username_selector: 'input[name="email"]'
      password_selector: 'input[name="pass"]'
    click_location:   # Change the location if your screen size is different, this will work as is for 1900x1280
      default_screen_height: 1280
      x_from_left: 1000
      y_from_bottom: 1000
    additional_args:
      additional_selector_1: 'text="Not now"'
      additional_selector_2: 'text="OK"'
  gmail:
    urls:
      - "https://accounts.google.com/"
      - "https://accounts.google.com/v3/signin/identifier/"
    username_selector: 'input[name="identifier"]'
    submit_selector: 'text="Next"'
    password_selector: 'input[name="Passwd"]'
    fall_back:
      password_selector: 'input[name="password"]'
    uses_2FA: True
    2FA_wait_value: "mail\\.google\\.com"

process_config:
  selectors :
    - "input:not([type='hidden']):not([type='submit']):not([type='button']):not([type='reset']):not([type='file'])"
    - "textarea"
    - "select"
    - "[contenteditable='true']"
    - "[role='textbox']"
    - "[role='searchbox']"
    - "[role='combobox']"