from typing import List

from pyba.core.lib import BaseEngine
from pyba.logger import get_logger
from pyba.utils.load_yaml import load_config

config = load_config("general")["main_engine_configs"]


class BFS_exploration(BaseEngine):
    """
    Methods for handling BFS exploratory searches

    Args:
            `plan_list`: A list of plans generated by the planner agent
            `prompt`: The request made by the user

    Note: This is an internal threading as opposed to the one shown in automation_eval
    """

    def __init__(self, plan_list: List, prompt: str):
        """
        Initialises the maximum number of workers and the result variable
        """
        self.plan_list = plan_list
        self.prompt = prompt
        self.log = get_logger()

        self.max_depth = config["max_depth"]
        self.max_breadth = config["max_breadth"]

        self.max_workers = min(5, len(plan_list))
        self.results = []

    def start_scan():
        pass
